Objetivo 0
sergioae19/SMITETracker pull request #1
Opened 2023-09-18 17:50 UTC by sergioae19

2023-09-18 18:21 UTC, JJ commented
Por favor, lee y sigue [las instrucciones relativas al título del PR y la inclusión de la lista de comprobación](http://jj.github.io/IV/documentos/proyecto/0.Repositorio)

También os expliqué en clase la importancia de los mensajes de commit, dos "primer commit" no son muy significativos. Por último, también debéis configurar la cuenta para que no figure el avatar por omisión.

2023-09-18 18:25 UTC, JJ requested changes
Por favor, consulta los [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md#con-respecto-a-los-problemas-enviados), en concreto este:

> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

En este caso, la formulación vaga es "me cuesta organizarme". Debes explicar claramente el contexto, y no entrar en "quiero un software que haga". Lo "que haga el software" en desarrollo ágil es algo que se va proponiendo y aprobando durante el proyecto. En esta etapa hay que formular claramente el problema, con todo el contexto que sea necesario para poder entenderlo.

`git-iv` tampoco tiene que estar en este repositorio, sino en tu path para poder ejecutarlo.

2023-09-19 05:47 UTC, JJ commented
Cuando esté listo, pide revisión.

2023-09-20 09:21 UTC, sergioae19 commented
@JJ solicito revisión cuando usted pueda.

2023-09-20 09:34 UTC, JJ requested changes
Salvo la eliminación del fichero, no hay ninguna mejora en la descripción del problema. Sigue siendo vago; "tengo muchas asignaturas".
Por favor, trata de prestar la atención debida a este objetivo, que debe ser la base sobre la que construyas la aplicación que te va a servir para comprender diferentes aspectos de la computación en la nube. Más allá de superar este objetivo o no, antes de solicitar evaluación pregúntate si esto te serviría a ti para comenzar a construir una aplicación para alguien.
Como mañana vamos a repetir el juego de rol si es necesario, te animo a que vengas a clase y participes para poder encontrar un problema con el que puedas seguir adelante en la asignatura.

2023-09-20 10:11 UTC, sergioae19 commented
@JJ solicito revisión cuando pueda

2023-09-20 10:21 UTC, JJ requested changes
Aparte de los errores de tecleo, que te rogaría que corrigieras, del [guión de este objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio), la lógica de negocio no debe incluir en su descripción cosas como:

> “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

En todo caso, sigue sin estar claro cuál es el problema, más allá de tener que convertir dos tiendas en una.

2023-09-20 10:58 UTC, sergioae19 commented
El principal problema es que en las tiendas hay miles de productos distintos pero poco stock de cada uno a parte de que sus padres no tienen capacidad de gestionar todo eso si no lo facilitamos.

2023-09-20 11:14 UTC, JJ commented
Gracias por contestar. A ver si nos podemos acercar a la resolución de este objetivo.

> El principal problema es que en las tiendas hay miles de productos distintos pero poco stock de cada uno a parte de que sus padres no tienen capacidad de gestionar todo eso si no lo facilitamos.

¿Te parece que ese sea un problema que se pueda resolver con una lógica de negocio sustancial en un programa y que se pueda hacer en esta asignatura? Te recuerdo también el [el tipo de problema no adecuado, de la FAQ](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#qué-tipo-de-problemas-no-van-a-ser-adecuados):

> Todos los problemas que requieran entradas físicas; todos aquellos en los que el usuario o cliente tenga que introducir mucha información. En general, todo problema que no se entienda bien.

En este caso, las existencias no queda otro remedio que hacerse mediante una entrada física.

En todo caso, tienes que especificar con más claridad y precisión el problema.

2023-09-20 11:25 UTC, sergioae19 commented
No entiendo por qué sería un problema que el usuario tenga que indrucir la cantidad de stock disponible... Podría explicarmelo?  Igualmente me gustaría mañana hablarlo con usted a ver si podemos resover el objetivo porque la verdad me haría bastante ilusión poder ayudar a mi compañero...

2023-09-20 11:39 UTC, JJ commented
Gracias por contestar. Vamos a intentar aclararlo.

> No entiendo por qué sería un problema que el usuario tenga que indrucir la cantidad de stock disponible... Podría explicarmelo? Igualmente me gustaría mañana hablarlo con usted a ver si podemos resover el objetivo porque la verdad me haría bastante ilusión poder ayudar a mi compañero...

Tú mismo has contestado así esta pregunta:

>  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* Sí, tengo todos los datos para resolver el problema.*

En [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) dice:

> No se va a ser suficientemente empático (como pide la metodología de design thinking) en un proyecto que requiera del usuario introducir gran cantidad de datos para obtener un resultado puntual.

También, un poco más arriba:

> De la misma forma, aplicaciones que tengan una dependencia externa fuerte (por ejemplo, que recojan datos de un API externo, que pidan una gran cantidad de datos al usuario o que simplemente integren una biblioteca externa para llevar a cabo una operación sobre datos también externos) tampoco van a ser buenos proyectos, porque sus pruebas van a ser complicadas y no van a incluir ningún tipo de modelo. 

En general, si el problema es llevar las existencias, es simplemente un programa de almacena y busca que, desde el principio, hemos dicho que no serían adecuados para esta asignatura (que requiere un procesamiento de datos medianamente complejo, para el objetivo 4).

El obstáculo para alcanzar el objetivo, en todo caso, no es ese. Es que no existe realmente un problema bien descrito con las características adecuadas para poder avanzar en las siguientes etapas del proyecto.

En general, para hallar y describir bien el problema hay que seguir una metodología como *design thinking*, que fue lo que tratamos de introducir en clase. Quizás lo más adecuado sea que repitamos mañana el juego en clase, si te parece bien; también puedes seguir esa metodología por tu cuenta.

2023-09-20 11:58 UTC, sergioae19 commented
Realmente, contabilizar las existencias no sería un problema, ya que eso está todo gestionado por los TPVs de las tiendas. El problema es que queremos que el usuario (sus padres) tenga la capacidad de poder actualizar la web añadiendo los productos nuevos conforme llegan a la tienda de la manera más fácil posible. Por ejemplo. una idea sería echar la foto al producto, añadirle el precio y que automáticamente se suba a la tienda online.

2023-09-20 12:33 UTC, JJ commented
> Realmente, contabilizar las existencias no sería un problema, ya que eso está todo gestionado por los TPVs de las tiendas. El problema es que queremos que el usuario (sus padres) tenga la capacidad de poder actualizar la web añadiendo los productos nuevos conforme llegan a la tienda de la manera más fácil posible. Por ejemplo. una idea sería echar la foto al producto, añadirle el precio y que automáticamente se suba a la tienda online.

Gracias por contestar, Sergio. Permíteme que insista en que "actualizar" no es un problema que sea adecuado como base de un proyecto para esta asignatura. Incluso aunque lo fuera, sigue teniendo una "dependencia externa fuerte": hacer fotos, por ejemplo. No estoy diciendo que no sea un problema interesante. Puede ser perfectamente un TFG. Pero [como dice en el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) necesitas un problema que necesite un valor añadido a los datos que tenga almacenados más allá de "actualizo un producto, tengo ese producto disponible". También comentas que se actualizaría con los TPVs de las tiendas. Una vez más, en el guión, dice:

> ¿Qué tipo de problemas no van a ser adecuados?

> *Todos los problemas que requieran entradas físicas; todos aquellos en los que el usuario o cliente tenga que introducir mucha información.*

En este objetivo hay que seguir una metodología de *design thinking* para precisar el problema, en concreto en la fase de empatía con el cliente. Puedes hacer esa fase tú mismo entrevistándote con ellos, y tratando de identificar qué problemas podrías tratar, problemas de los cuales puedan proporcionarte datos y con los cuales se pueda trabajar para realmente añadirle un valor. Puede ser predecir, puede ser organizar, puede ser cualquier otro procesamiento no trivial siempre que entiendas que tienes que programarlo tú y que será en el 4ª objetivo donde tendrás que probar que efectivamente tu procesamiento no trivial resuelve el problema especificado.

2023-09-20 17:14 UTC, JJ requested changes
En este objetivo no se trata de que os inventéis una aplicación a desarrollar. Se trata de que aprendáis a aplicar una metodología para describir un problema a resolver, de forma que esa descripción sea la base para inicial el desarrollo. En [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) describe un ejemplo de metodología, y en clase la hemos intentado aplicar con un juego de rol. Mañana lo vamos a repetir, por si pudieras asistir. Si no, trata de aplicar esa metodología por tu cuenta.
En todo caso, debéis pedir revisión explícitamente para que lo revise, no simplemente actualizarlo.

2023-09-20 17:14 UTC, JJ commented on README.md
> +Se necesita desarrollar un sistema de estadísticas para los usuarios de Smite que les permita acceder a información relevante, como el número de partidas ganadas, los personajes mas jugados o calcula
De [los errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md):

> Hablar desde el principio de "Quiero hacer una aplicación que haga..." cuando lo que se pide es que se describa un problema.

2023-09-20 17:24 UTC, sergioae19 commented
@JJ solicito revision

2023-09-20 17:29 UTC, JJ commented
Me vas a perdonar que insista, pero de lo que realmente se trata en este objetivo es que aprendáis a usar la metodología. En el tiempo que ha transcurrido desde la anterior evaluación es muy difícil que hayas aplicado o siquiera consultado de qué se trata. Siendo así, creo que vamos a entrar otra vez en el mismo bucle.
Si me confirmas que has intentado seguir la metodología para superar este objetivo, no tengo ningún inconveniente en corregirlo. Si no es así, te rogaría que lo hicieras. En esta asignatura el objetivo es que aprendáis a usar una serie de metodologías, no "que pongáis un problema".

2023-09-20 17:40 UTC, sergioae19 commented
Me gustaría que me lo corrigieras, sino mañana lo vemos en clase porque ya no se por donde tirar.

2023-09-23 07:31 UTC, JJ requested changes
Por favor, lee los [errores frecuentes](https://github.com/JJ/IV-/blob/master/sesiones/errores-objetivo-0.md). Para empezar, el problema no está claramente descrito. "No tener acceso" apenas es una descripción de pun problema.

Si quieres hacerlo en ese área porque es donde tienes conocimiento, trata de ver realmente qué problemas puede haber, si puede haber información poco estructurada que se pueda procesar, o si se puede aplicar algún algoritmo a algún aspecto de las estadísticas de jugadores; siempre, por supuesto, que las estadísticas de jugadores estén fácilmente disponibles ,

2023-09-27 06:32 UTC, JJ commented
¿Algún problema con esto? ¿Necesitas alguna aclaración?

2023-10-04 08:40 UTC, sergioae19 commented
Si perdona, he dejado un poco de lado algunas asignaturas por problemas en casa. He intentado describir mejor el problema y creo que si se puede aplicar algoritmos a las estadísticas de los jugadores, como por ejemplo ordenarlos por mejor KDA, horas que juegan algún personaje...

2023-10-04 09:23 UTC, JJ requested changes
Por favor, trata de precisar un poco más cuál es el problema.

2023-10-04 09:23 UTC, JJ commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
¿Estás diciendo entonces que esa información está en alguna página web de forma poco estructurada y que habría que aplicar algún algoritmo para extraerla haciendo scraping o usando expresiones regulares?

2023-10-04 09:37 UTC, sergioae19 commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
La página web no está mal estructurada pero tenemos que ir jugador a jugador investigando , a parte de que hay mucha información que a nosotros nos parece irrelevante. La página web es la siguiente: https://smite.guru/  por si quiere echarle un vistazo.

2023-10-04 09:41 UTC, JJ commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
No es que esté mal estructurada, es que esté poco estructurada y por lo tanto haya que extraer los datos que necestias del HTML, así como el URL de las personas que te interesan también de otra página web
![Captura de pantalla de 2023-10-04 11-40-07](https://github.com/sergioae19/SMITETracker/assets/500/6c55799e-da9a-41d5-a881-db44872e3e57)
Extraer números de aquí sería un ejemplo de extraer información poco estructurada.

Por lo que veo, los URLs también https://smite.guru/profile/14217994-Valakzz incluyen información que no se saca estrictamente del nombre del usuario, así que sería otra cosa que habría que extraer.

Si eso es lo que andas buscando, por favor, explícalo así.

2023-10-04 09:56 UTC, sergioae19 commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
Si, sería extraer los datos del HTML más relevantes y tener un resumen de los cinco jugadores que componen el equipo rival.
No sé si se refiere a que explique todo esto en la descripción del problema.

2023-10-04 09:57 UTC, JJ commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
Por supuesto. Si no, ¿cómo se entiende cuál es el verdadero problema?

2023-10-04 10:06 UTC, sergioae19 commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
De acuerdo, hecho.

2023-10-04 10:07 UTC, JJ approved these changes
:white_check_mark:

2023-10-04 10:07 UTC, JJ commented on README.md
> +Como comunidad competitiva del videojuego SMITE, tenemos un problema común, y es que no hay información fácilmente accesible de jugadores y equipos rivales. Nos gustaría tener alguna forma de acceder
irrelevante*s*

2023-10-11 09:32 UTC, JJ commented
Ya está aprobado, deberías fusionarlo y comenzar lo antes posible con el objetivo siguiente.

2023-10-11 11:43 UTC, sergioae19 commented
Sí, esta tarde tengo pensado ponerme.

2023-10-11 11:47 UTC, JJ commented
> Sí, esta tarde tengo pensado ponerme.

Por favor, no pierdas de vista los [plazos estimados](http://jj.github.io/IV/documentos/proyecto/1.Planificacion#plazo-de-entrega).

2023-10-19 11:46 UTC, JJ commented
Deberías fusionar esto y ponerte con el objetivo siguiente lo antes posible. Si no, va a ser muy cumplicado que llegues a los objetivos mínimos a tiempo.

2023-11-06 17:32 UTC, JJ commented
Por favor, fusiona esto ya, y también fusiona de main a la rama del objetivo 1

2023-11-06 17:50 UTC, merged